[package]
name = "mars"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30"
libc = "0.2"
objc2 = "0.5"
objc2-app-kit = { version = "0.2", features = ["all"] }
objc2-foundation = { version = "0.2", features = ["all"] }
objc2-metal = { version = "0.2", features = ["all"] }
objc2-quartz-core = { version = "0.2", features = ["all", "objc2-metal"] }
raw-window-handle = "0.6"
core-text = "21.0"
core-graphics = "0.24"
core-foundation = "0.10"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
