//! Session: one independent terminal instance.
//!
//! A Session owns its own PTY (and the child shell), its own Terminal
//! state machine + grid, and its own bounded mpsc channel fed by a
//! dedicated reader thread.  It is **deliberately ignorant of the
//! caller**: it knows nothing about windows, layouts, sidebars, or
//! event-loop event types.
//!
//! The caller supplies a `wake` callback that the reader thread invokes
//! whenever new bytes are available (or the child has exited).  The
//! caller's event loop then calls [`Session::pump`] to drain those
//! bytes through the parser into the grid.  This decoupling is what
//! lets the same Session power both `marspot` (multi-terminal grid app)
//! and `mcli` (single-terminal standalone app).

use std::io;
use std::os::raw::c_int;
use std::os::unix::io::RawFd;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc::{self, Receiver, SyncSender};
use std::sync::Arc;
use std::sync::OnceLock;
use std::thread::{self, JoinHandle};
use std::time::{Duration, Instant};

/// Once-per-process: write the ZDOTDIR shim that disables zsh's
/// `PROMPT_SP` option (and clears `PROMPT_EOL_MARK` as belt-and-
/// braces) so the very first prompt of every fresh session doesn't
/// open with a reverse-video `%`. Sources the user's real `.zshrc`
/// first so their normal init still runs.
///
/// Used to live in `marspot`'s `main.rs`; moved here so every binary
/// that calls `Session::spawn` — current and future — picks up the
/// same shell sanitisation automatically. `mcli` and `marspot` are
/// in lockstep here as a result.
fn install_shell_zdot_shim() {
    let home = match std::env::var("HOME") {
        Ok(h) => h,
        Err(_) => return,
    };
    let dir = std::path::PathBuf::from(&home).join(".cache/marspot/zdot");
    if std::fs::create_dir_all(&dir).is_err() {
        return;
    }
    // Write/overwrite the shim every launch so updates ship without
    // user intervention. Body is short + deterministic.
    let shim = r#"# Auto-generated by marspot: ZDOTDIR shim that sources the user's
# real .zshrc, then disables zsh's PROMPT_SP option (and clears
# PROMPT_EOL_MARK as belt-and-braces) so fresh sessions don't show a
# reverse-video "%" mark before the prompt.
[[ -f "$HOME/.zshrc" ]] && source "$HOME/.zshrc"
unsetopt PROMPT_SP 2>/dev/null
PROMPT_EOL_MARK=""
# zsh 5.9 defaults zle_highlight to include paste:standout, which wraps
# bracketed-paste content in `\e[7m ... \e[27m`.  When the user later
# recalls a pasted entry (Up arrow) or pastes the same content twice,
# ZLE re-emits the standout wrappers and some redraw paths fail to
# emit a final reset — leaving reverse-video stuck on the grid.  Drop
# the visual marker (self-use shells already know what they pasted).
# Done in a function so it runs AFTER zle is initialized; assigning
# at top-level can race with plugins that mutate zle_highlight later.
() { zle_highlight=(paste:none) } 2>/dev/null
# F3+3.6 — OSC 7 cwd push retired.  Modal pulls cwd via
# `proc_pidinfo` only when the user opens it.  The hook used to live
# here as `__marspot_osc7`.
"#;
    let _ = std::fs::write(dir.join(".zshrc"), shim);
    // Setting ZDOTDIR also reroutes .zshenv / .zprofile / .zlogin to
    // ZDOTDIR/* — without these shims the user's per-user env (PATH
    // additions, NVM init, asdf, etc.) would silently fail to load.
    // Each forwarder is a no-op when the upstream file is absent.
    let _ = std::fs::write(
        dir.join(".zshenv"),
        "[[ -f \"$HOME/.zshenv\" ]] && source \"$HOME/.zshenv\"\n",
    );
    let _ = std::fs::write(
        dir.join(".zprofile"),
        "[[ -f \"$HOME/.zprofile\" ]] && source \"$HOME/.zprofile\"\n",
    );
    let _ = std::fs::write(
        dir.join(".zlogin"),
        "[[ -f \"$HOME/.zlogin\" ]] && source \"$HOME/.zlogin\"\n",
    );
    // SAFETY: called from `ensure_shell_zdot_shim_installed` which
    // gates this through OnceLock; only fires the first time any
    // binary calls Session::spawn, before that binary spawns reader
    // threads or PTY children. Env-var change is inherited by every
    // subsequent forkpty child.
    unsafe { std::env::set_var("ZDOTDIR", &dir) };
    // When marspot is launched by LaunchServices (Dock / Spotlight /
    // double-click .app) it inherits TERM from launchd's session,
    // which on macOS resolves to "network" — a non-terminal value
    // that powerlevel10k, oh-my-zsh themes, and most TUIs interpret
    // as "no terminal" and refuse to render fancy prompts.  When
    // launched from another terminal (iTerm2, Terminal.app, a
    // parent shell, etc.) TERM is already a sensible terminfo entry
    // and we shouldn't clobber it.  Override only when the inherited
    // value is missing or obviously wrong; standard terminfo names
    // (xterm-*, screen-*, tmux-*, vt100, etc.) pass through.
    let term_ok = std::env::var("TERM")
        .map(|t| {
            !t.is_empty()
                && t != "network"
                && t != "dumb"
                && t != "unknown"
        })
        .unwrap_or(false);
    if !term_ok {
        unsafe { std::env::set_var("TERM", "xterm-256color") };
    }
    // Advertise 24-bit colour so apps emit truecolor (38;2;r;g;b) instead
    // of downgrading to the 256-colour cube (whose approximations shift
    // hues — e.g. Claude Code's coral orange → rose/pink at cube index
    // 174).  marspot renders truecolor, so claim it.  Leave a pre-set
    // value alone (a parent terminal may know better).
    if std::env::var_os("COLORTERM").is_none() {
        unsafe { std::env::set_var("COLORTERM", "truecolor") };
    }
}

/// Public entry point so binaries that spawn shells outside the
/// `Session::spawn` path (notably `marspot-shelld`) can still drop
/// the ZDOTDIR shim + TERM override into their environment before
/// the first fork.  Internally just delegates to the same idempotent
/// once-per-process installer.
pub fn ensure_zdot_shim_for_external_shells() {
    ensure_shell_zdot_shim_installed();
}

/// Idempotent gate around `install_shell_zdot_shim`. `Session::spawn`
/// calls this so every binary in the workspace (mcli, marspot, future
/// binaries) gets identical shell-init behavior without each having
/// to remember to call it at main().
fn ensure_shell_zdot_shim_installed() {
    static INSTALLED: OnceLock<()> = OnceLock::new();
    INSTALLED.get_or_init(install_shell_zdot_shim);
}

/// "Output produced within this window ⇒ Active, else Idle."  Two
/// seconds is short enough to feel live (a `make` finishing pulses
/// the dot) without flickering on every keystroke echo.
const ACTIVE_WINDOW: Duration = Duration::from_secs(2);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SessionState {
    /// Produced output recently (within ACTIVE_WINDOW).
    Active,
    /// Alive, child process still running, but quiet.
    Idle,
    /// Reader thread saw EOF — child has exited.  Final-frame contents
    /// remain readable but no new bytes will arrive.
    Exited,
}

use crate::pty::{Pty, PtyConfig, TerminalSize};
use crate::terminal::Terminal;

/// Bytes per chunk handed off from the reader thread.  64 KiB is the
/// opportunistic upper bound — for interactive output we send what
/// arrived; for bulk output we keep reading non-blocking until the PTY
/// drains, coalescing into one chunk before incurring the per-event
/// dispatch cost on the caller's main loop.
const READ_BUF: usize = 64 * 1024;

/// PTY reader instrumentation, for `--bench pty-drain` / `pty-feed`.
///
/// The question these answer: how many bytes does one `read(2)` on a
/// pty master actually return, and how many of them does one wakeup
/// gather?  On macOS the kernel tty output queue hands the master
/// roughly a kilobyte at a time regardless of the buffer offered, so a
/// reader that sleeps in `poll` after every drained queue runs in
/// lockstep with the writer at ~1 KiB per wakeup — a shape that is
/// invisible in throughput numbers alone and obvious in these counts.
///
/// Relaxed adds on a path that is already making a syscall; the cost
/// does not show up against a `read`.
#[cfg(feature = "bench-pty")]
pub static PTY_READ_CALLS: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
#[cfg(feature = "bench-pty")]
pub static PTY_READ_BYTES: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
#[cfg(feature = "bench-pty")]
pub static PTY_GATHER_BATCHES: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);

/// Bounded capacity of each session's PTY → caller channel.  When full
/// the reader thread blocks on send, propagating backpressure to the
/// kernel pipe buffer to the child's writes — bounded memory cost no
/// matter how fast the child writes.
const PTY_CHANNEL_CAPACITY: usize = 64;

pub struct Session {
    pub terminal: Terminal,
    pty: Pty,
    rx: Receiver<Vec<u8>>,
    exited: Arc<AtomicBool>,
    /// Wall-clock instant of the most recent byte fed to the terminal.
    /// Drives "recently active" indicators in any UI built on top.
    pub last_output: Option<Instant>,
    /// JoinHandle for the PTY reader thread.  `Drop` takes it,
    /// signals shutdown via `shutdown_pipe_w`, and joins before
    /// letting `Pty` close `master_fd` — without this, a fast
    /// "close pane → open pane" sequence can land the new pty's
    /// master fd on the same integer the dying reader is still
    /// blocked in `read()` on, leaking a few bytes from the new
    /// session into the dead one's channel.
    reader_handle: Option<JoinHandle<()>>,
    /// Write end of an internal pipe whose read end the reader
    /// thread polls alongside `master_fd`.  Writing a single byte
    /// wakes the reader out of `poll()` so it can observe `exited`
    /// and return.  Closed by `Drop` after the reader joins.
    shutdown_pipe_w: RawFd,
}

impl Session {
    /// Spawn a new session: forkpty into the user's shell, start a
    /// reader thread that pumps bytes into a bounded channel and calls
    /// `wake` on each chunk and once on EOF.
    ///
    /// The shell is `MARSPOT_SHELL` → `$SHELL` → `/bin/zsh`, in that order.
    /// `wake` typically posts a user event into the caller's event loop
    /// so the main thread comes around to call [`pump`](Self::pump).
    pub fn spawn<W>(cols: u16, rows: u16, wake: W) -> io::Result<Self>
    where
        W: Fn() + Send + Sync + 'static,
    {
        // MARSPOT_SHELL override path (tests, bench workers): direct exec
        // with a login-style argv[0].  No /usr/bin/login wrapper here
        // — the caller picked a specific program (often a shell
        // script), and login would refuse to exec a non-login-shell.
        if let Ok(custom_shell) = std::env::var("MARSPOT_SHELL") {
            let argv0 = format!(
                "-{}",
                std::path::Path::new(&custom_shell)
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or("sh")
            );
            return Self::spawn_with_config(
                &custom_shell, &[], Some(argv0), cols, rows, wake,
            );
        }
        // Real interactive use: wrap via /usr/bin/login -fpl so
        // "Last login: ..." is printed (terminating in \r\n) before
        // the shell starts.  Without that priming \n, zsh's PROMPT_SP
        // option fires on the first prompt and renders a reverse-video
        // "%" at the top of every fresh session.  iTerm2 /
        // Terminal.app spawn through login for the same reason; marspot
        // now matches.
        //   -f  no password
        //   -p  preserve env
        //   -l  exec the supplied shell
        // login itself sets argv[0] = "-<shellname>" before exec'ing
        // the shell, so we don't need our own argv0 override here.
        let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/zsh".into());
        let user = std::env::var("USER")
            .or_else(|_| std::env::var("LOGNAME"))
            .unwrap_or_else(|_| "nobody".into());
        Self::spawn_with_config(
            "/usr/bin/login",
            &["-fpl", &user, &shell],
            None,
            cols,
            rows,
            wake,
        )
    }

    /// Spawn variant with explicit program + args.  Useful for tests
    /// (no env-var racing) and for any future "open this session
    /// running <command>" UI affordance.
    pub fn spawn_with<W>(
        program: &str,
        args: &[&str],
        cols: u16,
        rows: u16,
        wake: W,
    ) -> io::Result<Self>
    where
        W: Fn() + Send + Sync + 'static,
    {
        Self::spawn_with_config(program, args, None, cols, rows, wake)
    }

    fn spawn_with_config<W>(
        program: &str,
        args: &[&str],
        argv0: Option<String>,
        cols: u16,
        rows: u16,
        wake: W,
    ) -> io::Result<Self>
    where
        W: Fn() + Send + Sync + 'static,
    {
        // Every spawn path funnels through this fn — put the once-
        // per-process ZDOTDIR shim install here so neither `spawn`
        // nor `spawn_with` need to remember to call it (and so any
        // future binary calling Session::spawn gets the same shell
        // sanitisation automatically).
        ensure_shell_zdot_shim_installed();

        // Default cwd to $HOME so a freshly-spawned shell opens where
        // the user expects.  LaunchServices-launched marspot inherits
        // cwd = `/`, which would otherwise leave every new shell in
        // the root directory.  Falls back to the inherited cwd (None)
        // when HOME is unset.
        let cwd = std::env::var("HOME").ok();
        let pty = Pty::spawn(PtyConfig {
            program: program.into(),
            args: args.iter().map(|s| (*s).to_string()).collect(),
            size: TerminalSize {
                cols,
                rows,
                pixel_width: 0,
                pixel_height: 0,
            },
            argv0,
            cwd,
            // Marspot's process-plumbing env (MARSPOT_SESSION_ID,
            // shm/surface ids, …) must not leak into the user's
            // shell — see PtyConfig::env_remove_prefixes.
            env_remove_prefixes: vec!["MARSPOT_".into()],
        })?;
        let (tx, rx) = mpsc::sync_channel::<Vec<u8>>(PTY_CHANNEL_CAPACITY);
        let exited = Arc::new(AtomicBool::new(false));
        // Self-pipe so Drop can wake the reader without using a
        // process-wide signal handler.  `pipe2` isn't on macOS, use
        // `pipe` + `fcntl(FD_CLOEXEC)`.  The read end is owned by
        // the reader thread (closed when it exits); the write end is
        // owned by `Session` and closed in `Drop` after `join`.
        let mut pipe_fds: [c_int; 2] = [-1, -1];
        if unsafe { libc::pipe(pipe_fds.as_mut_ptr()) } < 0 {
            return Err(io::Error::last_os_error());
        }
        let (shutdown_r, shutdown_w) = (pipe_fds[0], pipe_fds[1]);
        // FD_CLOEXEC so a forked child doesn't accidentally inherit
        // these and keep them alive past Drop's close().
        unsafe {
            libc::fcntl(shutdown_r, libc::F_SETFD, libc::FD_CLOEXEC);
            libc::fcntl(shutdown_w, libc::F_SETFD, libc::FD_CLOEXEC);
        }
        let reader_handle = spawn_reader(
            pty.raw_master(),
            shutdown_r,
            tx,
            exited.clone(),
            wake,
        );
        Ok(Self {
            terminal: Terminal::new(cols, rows),
            pty,
            rx,
            exited,
            last_output: None,
            reader_handle: Some(reader_handle),
            shutdown_pipe_w: shutdown_w,
        })
    }

    /// Drain whatever bytes the reader thread has queued into this
    /// session's terminal.  Returns the total bytes fed.  Caller should
    /// trigger a redraw when the return value is non-zero.
    pub fn pump(&mut self) -> usize {
        let mut total = 0;
        while let Ok(chunk) = self.rx.try_recv() {
            total += chunk.len();
            self.terminal.feed(&chunk);
        }
        if total > 0 {
            self.last_output = Some(Instant::now());
        }
        // Forward any capability-query responses (DA, XTQVERSION, etc.)
        // the terminal queued during this feed cycle back to the PTY so
        // the app's read() returns them. Apps that stall waiting for a
        // DA response otherwise fall back to degraded rendering paths
        // (extra blank rows, misaligned chrome).
        let response = self.terminal.take_response();
        if !response.is_empty() {
            let _ = self.write(&response);
        }
        total
    }

    /// Drain pending bytes from the reader thread *without* feeding
    /// the terminal.  The caller takes responsibility for routing —
    /// useful when something other than the VT parser owns the byte
    /// stream first (e.g. tmux control mode, where `tmux::Parser`
    /// extracts the per-pane output that then goes to `feed_terminal`).
    pub fn drain_raw(&mut self) -> Vec<u8> {
        let mut out = Vec::new();
        while let Ok(chunk) = self.rx.try_recv() {
            out.extend_from_slice(&chunk);
        }
        if !out.is_empty() {
            self.last_output = Some(Instant::now());
        }
        out
    }

    /// Feed bytes directly into this session's terminal, bypassing
    /// the channel.  Companion to [`drain_raw`](Self::drain_raw):
    /// after the caller's own parser has extracted the payload bytes
    /// from a wire-format chunk, those bytes are handed back here.
    pub fn feed_terminal(&mut self, bytes: &[u8]) {
        self.terminal.feed(bytes);
    }

    /// True after the reader thread has observed EOF on the PTY master
    /// (i.e. the child shell exited).  The terminal's final-frame
    /// contents remain readable; callers may keep displaying them.
    pub fn is_exited(&self) -> bool {
        self.exited.load(Ordering::Acquire)
    }

    /// Write keystroke / paste bytes back to the child.
    pub fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
        self.pty.write(bytes)
    }

    /// Resize the terminal grid + the PTY winsize.  The shell receives
    /// SIGWINCH and repaints accordingly.
    pub fn resize(&mut self, cols: u16, rows: u16) {
        self.terminal.resize(cols, rows);
        let _ = self.pty.resize(TerminalSize {
            cols,
            rows,
            pixel_width: 0,
            pixel_height: 0,
        });
    }

    /// Borrow the terminal for reading (used by render).
    pub fn terminal(&self) -> &Terminal {
        &self.terminal
    }

    /// Roll up `is_exited()` + `last_output` into a single state suitable
    /// for the sidebar's status dot.  See [`SessionState`].
    pub fn state(&self) -> SessionState {
        if self.is_exited() {
            return SessionState::Exited;
        }
        match self.last_output {
            Some(t) if t.elapsed() < ACTIVE_WINDOW => SessionState::Active,
            _ => SessionState::Idle,
        }
    }
}

fn spawn_reader<W>(
    master_fd: RawFd,
    shutdown_fd: RawFd,
    tx: SyncSender<Vec<u8>>,
    exited: Arc<AtomicBool>,
    wake: W,
) -> JoinHandle<()>
where
    W: Fn() + Send + Sync + 'static,
{
    thread::Builder::new()
        .name("marspot-pty-reader".into())
        .spawn(move || {
            let mut buf = [0u8; READ_BUF];
            loop {
                // Block on either fd via poll() so we can be woken
                // out of an idle wait without anyone closing
                // master_fd — `Session::drop` writes one byte to
                // `shutdown_fd` to break us out and lets us join
                // before the master fd closes.
                let mut pfds = [
                    libc::pollfd {
                        fd: master_fd,
                        events: libc::POLLIN,
                        revents: 0,
                    },
                    libc::pollfd {
                        fd: shutdown_fd,
                        events: libc::POLLIN,
                        revents: 0,
                    },
                ];
                let r = unsafe { libc::poll(pfds.as_mut_ptr(), 2, -1) };
                if exited.load(Ordering::Acquire) {
                    break;
                }
                if r < 0 {
                    let err = io::Error::last_os_error();
                    if err.kind() == io::ErrorKind::Interrupted {
                        continue;
                    }
                    break;
                }
                if pfds[1].revents & (libc::POLLIN | libc::POLLHUP | libc::POLLERR | libc::POLLNVAL) != 0 {
                    // Shutdown signaled; exit before touching
                    // master_fd in case it's already on its way to
                    // being closed.
                    break;
                }
                let master_re = pfds[0].revents;
                if master_re & libc::POLLIN == 0 {
                    // POLLHUP / POLLERR / POLLNVAL without data —
                    // child exited or fd closed externally.
                    if master_re & (libc::POLLHUP | libc::POLLERR | libc::POLLNVAL) != 0 {
                        exited.store(true, Ordering::Release);
                        wake();
                    }
                    break;
                }

                let n = unsafe {
                    libc::read(
                        master_fd,
                        buf.as_mut_ptr() as *mut libc::c_void,
                        buf.len(),
                    )
                };
                #[cfg(feature = "bench-pty")]
                {
                    PTY_GATHER_BATCHES.fetch_add(1, Ordering::Relaxed);
                    PTY_READ_CALLS.fetch_add(1, Ordering::Relaxed);
                    if n > 0 {
                        PTY_READ_BYTES.fetch_add(n as u64, Ordering::Relaxed);
                    }
                }
                if n <= 0 {
                    exited.store(true, Ordering::Release);
                    wake();
                    break;
                }
                let mut total = n as usize;

                // Opportunistic drain: poll(0) and read whatever else is
                // already in the kernel pipe.  Cuts IPC × dispatch cost
                // on bulk output without adding latency to interactive
                // output (single byte sent immediately because poll
                // says "no more").
                while total < buf.len() {
                    let mut pfd = libc::pollfd {
                        fd: master_fd,
                        events: libc::POLLIN,
                        revents: 0,
                    };
                    let ready = unsafe { libc::poll(&mut pfd, 1, 0) };
                    if ready <= 0 {
                        break;
                    }
                    let n2 = unsafe {
                        libc::read(
                            master_fd,
                            buf.as_mut_ptr().add(total) as *mut libc::c_void,
                            buf.len() - total,
                        )
                    };
                    #[cfg(feature = "bench-pty")]
                    {
                        PTY_READ_CALLS.fetch_add(1, Ordering::Relaxed);
                        if n2 > 0 {
                            PTY_READ_BYTES.fetch_add(n2 as u64, Ordering::Relaxed);
                        }
                    }
                    if n2 <= 0 {
                        break;
                    }
                    total += n2 as usize;
                }

                let chunk = buf[..total].to_vec();
                if tx.send(chunk).is_err() {
                    break;
                }
                wake();
            }
            // Reader owns the read end of the shutdown pipe; close on
            // exit so the kernel can reclaim it.
            unsafe { libc::close(shutdown_fd) };
        })
        .expect("spawn pty reader thread")
}

impl Drop for Session {
    fn drop(&mut self) {
        // Wake the reader.  exited=true is observed after poll
        // unblocks; the pipe write is what makes poll unblock without
        // touching master_fd.
        self.exited.store(true, Ordering::Release);
        let _ = unsafe {
            libc::write(self.shutdown_pipe_w, b"x".as_ptr() as *const _, 1)
        };
        if let Some(handle) = self.reader_handle.take() {
            // join() blocks until the reader's thread function
            // returns.  Rust drops fields in declaration order AFTER
            // this Drop body returns, so Pty (which closes master_fd)
            // drops only after we've already joined — the reader is
            // guaranteed to be off the fd before close, eliminating
            // the fd-reuse race.
            let _ = handle.join();
        }
        // Reader has closed its read end; close our write end.
        unsafe { libc::close(self.shutdown_pipe_w) };
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::AtomicUsize;
    use std::time::Duration;

    /// Spin until `pred` returns true or `deadline_ms` elapses.  Pumps
    /// the session each tick so the test sees fresh state.  Returns
    /// the time taken (or panics on timeout).
    fn spin_until<F: FnMut(&mut Session) -> bool>(
        s: &mut Session,
        deadline_ms: u64,
        mut pred: F,
    ) -> Duration {
        let start = std::time::Instant::now();
        loop {
            s.pump();
            if pred(s) {
                return start.elapsed();
            }
            if start.elapsed() > Duration::from_millis(deadline_ms) {
                panic!("spin_until timed out after {} ms", deadline_ms);
            }
            std::thread::sleep(Duration::from_millis(5));
        }
    }

    fn first_row(s: &Session) -> String {
        let g = s.terminal.grid();
        (0..g.cols()).map(|c| g.cell(c, 0).ch).collect()
    }

    /// Concatenate every row of the visible grid into one string.
    /// Useful for tests that don't care which line a substring landed
    /// on (PTY echo + shell stdout can split a single round-trip
    /// across rows).
    fn all_rows(s: &Session) -> String {
        let g = s.terminal.grid();
        let mut out = String::new();
        for r in 0..g.rows() {
            for c in 0..g.cols() {
                out.push(g.cell(c, r).ch);
            }
            out.push('\n');
        }
        out
    }

    #[test]
    fn spawn_with_runs_to_eof_and_marks_exited() {
        // `/bin/sh -c 'true'` exits immediately; the reader thread sees
        // EOF, sets the exited flag, and fires the wake callback.
        let woke = Arc::new(AtomicUsize::new(0));
        let woke_clone = woke.clone();
        let mut s = Session::spawn_with(
            "/bin/sh",
            &["-c", "true"],
            40,
            10,
            move || {
                woke_clone.fetch_add(1, Ordering::Relaxed);
            },
        )
        .expect("spawn");

        spin_until(&mut s, 1000, |s| s.is_exited());
        assert!(s.is_exited());
        // EOF wake always fires; reader-thread chunks may add more.
        assert!(woke.load(Ordering::Relaxed) >= 1);
    }

    #[test]
    fn pump_feeds_bytes_into_terminal_grid() {
        let mut s = Session::spawn_with(
            "/bin/sh",
            &["-c", "printf hello && exit"],
            40,
            10,
            || {},
        )
        .expect("spawn");

        spin_until(&mut s, 1000, |s| first_row(s).starts_with("hello"));
        assert!(first_row(&s).starts_with("hello"));
    }

    #[test]
    fn write_round_trips_through_pty() {
        // `stty -echo` so PTY won't echo our input back as a separate
        // visible line; output ends up with just shell's printf result.
        let mut s = Session::spawn_with(
            "/bin/sh",
            &["-c", "stty -echo; read line; printf '<%s>' \"$line\""],
            40,
            10,
            || {},
        )
        .expect("spawn");

        // Give stty time to apply before we write.
        std::thread::sleep(Duration::from_millis(50));
        s.write(b"sentinel\n").expect("write");

        spin_until(&mut s, 1500, |s| all_rows(s).contains("<sentinel>"));
        assert!(all_rows(&s).contains("<sentinel>"));
    }

    #[test]
    fn pump_returns_zero_when_no_data_pending() {
        // Use `sleep` so the child stays alive but never writes.
        let mut s = Session::spawn_with("/bin/sh", &["-c", "sleep 5"], 40, 10, || {})
            .expect("spawn");

        // Give the reader thread a moment to settle, then pump should
        // find nothing in the channel.
        std::thread::sleep(Duration::from_millis(50));
        assert_eq!(s.pump(), 0);
        assert!(!s.is_exited());

        // Drop the session — Pty::drop reaps the sleep child.
        drop(s);
    }

    #[test]
    fn resize_propagates_to_terminal_grid() {
        let mut s = Session::spawn_with("/bin/sh", &["-c", "sleep 5"], 40, 10, || {})
            .expect("spawn");
        assert_eq!(s.terminal.grid().cols(), 40);
        assert_eq!(s.terminal.grid().rows(), 10);
        s.resize(60, 20);
        assert_eq!(s.terminal.grid().cols(), 60);
        assert_eq!(s.terminal.grid().rows(), 20);
    }
}
